name: Simple NPM Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '3.1.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Create package.json
        run: |
          cat > package.json << EOF
          {
            "name": "chainwise",
            "version": "${{ github.event.inputs.version }}",
            "description": "Universal Multi-Blockchain HD Wallet Library",
            "main": "dist/chainwise.min.js",
            "files": ["dist/chainwise.min.js", "README.md"],
            "keywords": ["blockchain", "wallet", "crypto", "multi-chain"],
            "author": "ChainWise Team",
            "license": "MIT",
            "repository": {
              "type": "git",
              "url": "https://github.com/${{ github.repository }}.git"
            }
          }
          EOF

      - name: Verify file exists
        run: ls -la chainwise.min.js

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}